<?php


namespace App\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ProcessInvoices extends Command
{
    protected static $defaultName = 'app:invoices:process';

    protected function configure()
    {
        // Set command description.
        $this->setDescription('Processes the invoices');

        // Set command help.
        $this->setHelp('Processes the invoices. Generates an invoice as txt an as xml');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
